# Site settings
title: "FluentMind - Documentação Técnica"
description: "Plataforma de comunicação inteligente com IA para Salesforce"
url: "https://elton-santos.github.io"
baseurl: "/fluentmind"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  docs:
    output: true
    permalink: /:collection/:name/

header_pages:
  - overview.md
  - roadmap.md
  - architecture.md
  - data-model.md
  - functional-requirements.md
  - non-functional-requirements.md
  - git-workflow.md
  - development-standards.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

author: "Equipe FluentMind"
lang: "pt-BR"

github_username: elton-santos
